### ISSUE TITLE
Nice idea.

### ISSUE THREAD

**Issue by yechengxi** [shengliu66/ConvNorm#2]
I think this work is good. But please note that a similar idea behind the work has recently been explored -- we think the computations are in fact easier in the spatial domain. We appreciate if you could kindly discuss and cite our work.

https://openreview.net/pdf?id=rkeu30EtvS

**Comment by shengliu66** [comment]
Hi Chengxi,

Thank you so much for pointing this out. Indeed, our work is partially inspired by your interesting ICLR paper. We are very sorry that we missed the reference for your work. In future versions, we will make sure that your work is cited and discussed.

Sincerely,
Sheng

**Comment by yechengxi** [comment]
Thanks. It is quite common to come up with similar ideas these days. Thinking deeper and healthy discussion may in fact lead to new discoveries. Lookingforward to more interesting findings from you!
